### ISSUE TITLE
rmate ports

### ISSUE THREAD

**Issue by KES777** [textmate/rmate#45]
The official ruby version: https://github.com/textmate/rmate
    A bash version: https://github.com/aurora/rmate
    A perl version: https://github.com/davidolrik/rmate-perl
    A python version: https://github.com/sclukey/rmate-python
    A nim version: https://github.com/aurora/rmate-nim
    A C version: https://github.com/hanklords/rmate.c
    A node.js version: https://github.com/jrnewell/jmate

copied from: https://atom.io/packages/remote-atom

it willbe usefull if you add this info to the Readme file.

**Comment by sorbits** [comment]
Thanks, though I think this should come as a pull request from the various port maintainers, so that we are sure they actually want to be listed as a port in the official readme, and are likely to update their port when the official version is updated. For example a nim port of `rmate` sounds more like somebody just doing it for the fun of it, rather than serving an actual need (the first ports created was because not all servers have ruby 1.8).

**Comment by KES777** [comment]
FIrst time I google port of rmate on perl I found it after one month later... that is very usefull info.
May you mention about them as: you may also look at bash/perl/python/nic...  ?
In any case thanks to you too
